---
- name: download JDK8
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm
    mode: 0755
    validate_certs: no
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
- name: be sure JDK8 is installed
  yum:
    name: /tmp/jdk-8u131-linux-x64.rpm
    state: present
