---
- name: be sure docker is installed
  yum:
    name: docker
    state: present
- name: be sure docker is running and enabled
  service:
    name: docker
    state: started
    enabled: no
- name: install docker-compose
  pip:
    name: docker-compose
